name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        name: External PR Labeler
        if: ${{ github.event.pull_request.head.repo.full_name != 'tjololo/labler-test' }}
        with:
          configuration-path: .github/external-pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: TimonVS/pr-labeler-action@v3
        name: Internal PR Labeler
        if: ${{ github.event.pull_request.head.repo.full_name == 'tjololo/labler-test' }}
        with:
          configuration-path: .github/internal-pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}